Completed Task 3
opencodeiiita/HackerSkills pull request #10
Opened 2019-01-21 16:44 UTC by kesari007

Solves #6

2019-01-22 08:33 UTC, Jigar3 requested changes
Upload the data you got from scraping as well

2019-01-22 13:02 UTC, kesari007 commented
@Jigar3 upload as in? The BeautifulSoup object `soup` already has all the data in it though.

2019-01-22 13:03 UTC, Jigar3 commented
Save the object in a txt or JSON file and upload that

2019-01-22 13:46 UTC, kesari007 commented
okay sure.

2019-01-22 14:35 UTC, kesari007 commented
@Jigar3 I have made the changes, Please review it now.

2019-01-22 14:43 UTC, Jigar3 requested changes

2019-01-22 14:43 UTC, Jigar3 commented on Task 3/data.json
> +}{
Add comma after each entry

2019-01-22 16:03 UTC, kesari007 commented on Task 3/data.json
> +}{
Done @Jigar3

2019-01-23 10:30 UTC, kesari007 commented
@Jigar3 Please review now.

2019-01-25 18:49 UTC, closed without merging